spring.application.name=GestionUser
server.port=9020
server.servlet.context-path=/tpCours

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/testB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
