# Generated by Django 5.2.1 on 2025-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='brand',
        ),
        migrations.AddField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notebook_images/'),
        ),
    ]
